language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  # PyPy2 2.5.0
  # - "pypy-5.3.1"

install:
  - pip install coverage
  - pip install coveralls
  - pip install zope.interface
  - pip install -e .

script:
  - python -m unittest plumber.tests.test_plumber
  - coverage run --source src/plumber -m plumber.tests.test_plumber
  - coverage report

after_success:
  - coveralls
